version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lk_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lk_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: ./backend/.env.example
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file: ./frontend/.env.local.example
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
